#!/usr/local/bin/perl

# sorts on first two numeric columns
# works for scientific notation and decimals

while (<>) {
    ($val1, $val2, @rest) = split;
    $val1{$.} = $val1;
    $val2{$.} = $val2;
    $rest{$.} = join(' ', @rest);
};

foreach $ln (sort {$val1{$a} <=> $val1{$b} || $val2{$a} <=> $val2{$b}} 
	     keys %val1) {
    $outstring = "$val1{$ln} $val2{$ln} $rest{$ln}";
    $outstring =~ s/ *$//;
    print "$outstring\n";
};

	
